<template>
  <div>
    <form class="form-container" @submit.prevent="submitForm">
      <h1>E2EE Demo</h1>
      <FormHelpDescription text="This form allows you to submit a message. The message will be encrypted on the server, and you'll receive an encrypted response which only you can read but the server never keeps the secret." />
      <div>
        <label for="email">Spoof or real client ID:</label>
        <input type="email" id="email" placeholder="Try something or use your real one" v-model="formData.client_id" required>
      </div>
      <div>
        <label for="message">Message:</label>
        <textarea id="message" v-model="formData.message" required placeholder="Type anything to simulate E2EE
Normally this is generated by the other end, the point here is you can verify the server was able to encrypt a message that only you can ever read."></textarea>
      </div>
      <button type="submit">Send to server</button>
    </form>

    <div v-if="response">
      <h2>Response from Server:</h2>
      <p>{{ response }}</p>
    </div>
  </div>

</template>

<script setup>
import FormHelpDescription from '@/components/FormHelpDescription.vue';
</script>

<script>
export default {
  components: {
    FormHelpDescription
  },
  data() {
    return {
      formData: {
        client_id: '',
        message: ''
      },
      response: null
    };
  },
  methods: {
    async submitForm() {
      try {
        const response = await fetch('http://localhost:8000/encrypt-message', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            client_id: this.formData.client_id,
          })
        });

        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        this.response = data;
      } catch (error) {
        console.error('Error:', error);
        this.response = 'Error occurred while sending data to the server.';
      }
    }
  }
};
</script>

<style scoped lang="scss">
$form-background: #f5f5f5;
$form-border-color: #ddd;
$form-border-radius: 5px;
$button-color: teal;
$button-hover-color: darken($button-color, 10%);
$label-spacing: 5px;

.form-container {
  background-color: $form-background;
  border: 1px solid $form-border-color;
  border-radius: $form-border-radius;
  padding: 20px;
  margin: 0 auto;
  color: #1a1a1a;

  label {
    display: block;
    margin-bottom: $label-spacing;
  }

  input[type="email"],
  textarea {
    width: 100%;
    padding: 8px;
    border: 1px solid $form-border-color;
    border-radius: $form-border-radius;
    margin-bottom: 10px;
  }
  textarea {
    height: 150px;
  }

  button {
    background-color: $button-color;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: $form-border-radius;
    cursor: pointer;

    &:hover {
      background-color: $button-hover-color;
    }
  }
}
</style>
